name: shell commands

on: 
  - push
  
env:
  AWS_ACCESS_KEY: ${{ secret.AWS_ACCESS_KEY}}
  AWS_SECRET_ACCESS_KEY: ${{secret.AWS_SECRET_ACCESS_KEY}}

jobs:
   terraform-job:
     runs-on: ubuntu-latest
     steps:
        - name: checkout
          uses: actions/checkout@v1
        - name: set terraform
          uses: hashicorp/setup-terraform@v2
          with:
             terraform_version: 1.1.9
        - name: terraform initialisation
          run: terraform init
        - name: terraform validate
          run: terraform validate
        - name: terraform plan
          run: terraform plan
          
            
       

