name: shell commands

on: 
  - push
  

jobs:
   run-shell-commands:
     runs-on: ubuntu-latest
     steps:
        - name: checkout
          uses: action/checkout@v1
        - name: multi line string
          run: |
             pwd
             node -v
             ls -a
       

